---
title: "Master_2011_TS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
load("C:/Users/jackf/Desktop/Coding/R/Homeworks/5730 Homework 7/masters2011-untidy.rda")

Pipeline <- function(df,round){
  df %>%
    
    pivot_longer(c(`1`,`2`,`3`,`4`,`5`,`6`,`7`,`8`,`9`,
           `10`,`11`,`12`,`13`,`14`,`15`,`16`,`17`,`18`), names_to = "hole",values_to = "strokes") %>% 
    
  mutate(hole = as.double(hole)) %>%
    
  left_join(course) %>%
    
  mutate(score = strokes - par, round = round)
}

round1 <- Pipeline(round1,1)

round2 <- Pipeline(round2,2)

round3 <- Pipeline(round3,3)

round4 <- Pipeline(round4,4)

df <- rbind(round1,round2,round3,round4) %>% 
  select(player,round,hole,everything()) %>%
  arrange(player,round,hole)

df <- df %>%
  group_by(player) %>%
  summarise(cumulative_to_par=cumsum(score),
            player,
            hole,
            round) %>%
  inner_join(df) %>% 
  inner_join(leaderboard) %>%
  mutate(label = ifelse(position==1 & 
                        hole==18 & 
                        round==4
                        ,player,NA))



df %>%
  ggplot(aes(x=hole, 
             y=cumulative_to_par, 
             color=player, 
             label = label
             )) +
  geom_line() +
  facet_grid(.~round, labeller=label_both) +
  theme(legend.position='none') +
  scale_x_continuous(breaks=c(1,9,18)) +
  ggrepel::geom_label_repel()
```